version: '3.3'
services:
  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./tmp/data/db:/data/db
  blogbe:
    image: blogbe
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
